### ISSUE TITLE
Value passed back by installExtension is a JS Object not a name

### ISSUE THREAD

**Issue by mwoodpatrick** [MarshallOfSound/electron-devtools-installer#133]
In the docs the value passed back by installExtension is a JS Object not a name as implied by the parameter name and the console.log can we get the docs to clarify what data is being passed back something like:

```
installExtension(REACT_DEVELOPER_TOOLS)
      .then((ext) => {
        console.log(`Added Extension: "${ext.name}" version ${ext.version}`);
```

might be more useful

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
