### ISSUE TITLE
Devtools are not always loaded in all BrowserWindows

### ISSUE THREAD

**Issue by fakob** [MarshallOfSound/electron-devtools-installer#146]
In my electron app I create 2 BrowserWindows. I call installExtension after creating the BrowserWindows, but my main window only loads the devtools occasionally. 
```
app.whenReady()
.then(createWindows)
.then(() => {
    installExtension(REDUX_DEVTOOLS)
        .then((name) => console.log(`Added Extension:  ${name}`))
        .catch((err) => console.log('An error occurred: ', err));
});
```

Can I call installExtension on specific BrowserWindows or can I do anything differently so I do not have to rely on my luck on startup :-)

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
