### ISSUE TITLE
React DevTools fails to install with an Error: Exited with code 2

### ISSUE THREAD

**Issue by yourfavorite** [MarshallOfSound/electron-devtools-installer#148]
I'm trying to figure out the same issue that is covered here: https://github.com/facebook/react/issues/19430

I'm using the same code to load the extensions and getting the same code 2 error. I'm on windows running electron 8.5.0.

Thanks!

**Comment by CerratoA** [comment]
Hello, did you find any solution @yourfavorite ?

**Comment by yourfavorite** [comment]
@CerratoA Yes I did and I did it on accident trying to fix something else a while later. I forgot I had posted this or else I would have updated. As it's been a while since this happened I'm going loosely based on my memories. But if memory serves, I moved where I was calling devtools to open. Try moving `openDevTools()` inside of the `ready-to-show` event callback.

```
	// Emitted when window has finished first load
	mainWindow.once('ready-to-show', () => {
		if (mainWindow) mainWindow.show();
		mainWindow.webContents.openDevTools();
	});
```

**Comment by YvanBrito** [comment]
This problem was happening to me. Upgrade the version that I was using (2.2.4) to the latest version (3.1.1) as it was mentioned [here](https://github.com/MarshallOfSound/electron-devtools-installer/issues/157#issuecomment-704792363) worked for me

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
