### ISSUE TITLE
redux developer tools working very intermittently?

### ISSUE THREAD

**Issue by ericblade** [MarshallOfSound/electron-devtools-installer#160]
I'm really not sure even how to diagnose where this is going wrong -- I have an app that I had just built a tiny little html page out of as a simple prototype.  I decided that rebuild it with React/Redux/etc.  I'm attempting to use this package to install React and Redux dev tools .. I've now got React dev tools working well, but the Redux dev tools frequently just say "No store found. Make sure to follow the instructions."  If I open the application *outside* of Electron, in a regular web browser, the Redux dev tools work just fine.  

Sometimes, the Redux dev tools work, though if I refresh the page (via hot reload, or using ctrl-r to reload), then they will stop working.  

Regardless of if they work or not, I see this error on console after starting:

![image](https://user-images.githubusercontent.com/1451847/97998274-e4d02900-1db7-11eb-8c60-a79d90614f8e.png)

Any tips for any more things I can look into to help figure out what the problem might be and fix it?

**Comment by jameslh** [comment]
I have this same issue, but I did find that if I close the dev tools panel and then reopen it, then at least the redux panel will display correctly again without me having to restart the entire app.

**Comment by bennymeg** [comment]
To fix these errors you will need to pick up the new redux extension version.
You can update it by temporarily changing this line in our code:

```diff
- installExtension(REDUX_DEVTOOLS}});
+ installExtension(REDUX_DEVTOOLS, { forceDownload: true }});
```

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
