### ISSUE TITLE
Only Redux Shows! 

### ISSUE THREAD

**Issue by mustafaabobakr** [MarshallOfSound/electron-devtools-installer#161]
![image](https://user-images.githubusercontent.com/27288406/99874717-c0b37b00-2bf2-11eb-8048-a7bdafb17a87.png)

**Comment by MichaelSp** [comment]
duplicate #162 ?

**Comment by DoWhileGeek** [comment]
Any update on this? Just cloned the project.

**Comment by sahilbest999** [comment]
> duplicate #162 ?

yup

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
