### ISSUE TITLE
Devtools don't show on OSX

### ISSUE THREAD

**Issue by mboutin-qohash** [MarshallOfSound/electron-devtools-installer#174]
Hi! I'm working on an Electron app and I'm testing it on OSX and Windows.

Everything is fine on Windows but my 2 extensions doesn't show at all on OSX.

This is what I use:

```
const { default: installExtension, REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS } = require('electron-devtools-installer')

  installExtension(REACT_DEVELOPER_TOOLS)
    .then((name) => {
      log.debug(`Added Extension: ${name}`)
    })
    .catch((err) => {
      log.error('An error occurred: ', err)
    })

  installExtension(REDUX_DEVTOOLS)
    .then((name) => {
      log.debug(`Added Extension: ${name}`)
    })
    .catch((err) => {
      log.error('An error occurred: ', err)
    })
```

What can I check or change to have them on OSX?

**Comment by RoderickJDunn** [comment]
I had the same issue. I had to do 3 things to get both extensions to show up in devtools. 
1. Upgrade Electron - I was on 11.1 but had to upgrade to 11.3 
2. Install this package from github instead of npm. Run the command `yarn add git+https://github.com/MarshallOfSound/electron-devtools-installer.git` to install the latest on master.
3. Use the new option "loadExtensionOptions" and include "allowFileAccess: true" to the options passed into "installExtension", as follows: 
```
import installExtension, { REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS } from 'electron-devtools-installer';
...
const forceDownload = !!process.env.UPGRADE_EXTENSIONS;
const extensions = [REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS];
installExtension(
      extensions,
      {loadExtensionOptions: {allowFileAccess: true}, forceDownload: forceDownload}
    )
    .catch(console.log);
```

**Comment by yourfavorite** [comment]
@RoderickJDunn I gave your solution a try but the extensions aren't loading and I get a type error:
`TypeError: invalid options argument`

Did you run into this?

**Comment by RobinClowers** [comment]
I was able to get this working with `electron-devtools-installer` 3.2.0 and `electron` 11.4.7. It did not work with an earlier electron 11 release, FYI.

**Comment by schontz** [comment]
Even after cleaning up all the warnings and using @RoderickJDunn's suggestion, no dev tool extensions show up.

Electron v12.0.8
Node v14.15.4
Mac v10.15.17

**Comment by neilning-xc** [comment]
> I had the same issue. I had to do 3 things to get both extensions to show up in devtools.
> 
> 1. Upgrade Electron - I was on 11.1 but had to upgrade to 11.3
> 2. Install this package from github instead of npm. Run the command `yarn add git+https://github.com/MarshallOfSound/electron-devtools-installer.git` to install the latest on master.
> 3. Use the new option "loadExtensionOptions" and include "allowFileAccess: true" to the options passed into "installExtension", as follows:
> 
> ```
> import installExtension, { REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS } from 'electron-devtools-installer';
> ...
> const forceDownload = !!process.env.UPGRADE_EXTENSIONS;
> const extensions = [REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS];
> installExtension(
>       extensions,
>       {loadExtensionOptions: {allowFileAccess: true}, forceDownload: forceDownload}
>     )
>     .catch(console.log);
> ```

Thanks, it fixes the issue

**Comment by timothymalcham** [comment]
Following @RoderickJDunn's instructions allowed the redux dev tools to show up, but not the react dev tools. Has anybody else found a solution to this?

**Comment by f-o-w-l** [comment]
Redux has always shown up for me, but never React Dev Tools, though they're being installed the same way. Running Manjaro Linux, someone let me know if I should make another issue, not going to for now.

**Comment by ganeshrvel** [comment]
If anyone else is facing the same issue and is unable to get the package working on a mac Intel silicon you may use this:

```shell
yarn add  -D git+https://github.com/ganeshrvel/electron-devtools-installer.git#fix/electron-18
```

```js
import installExtension, {
  REDUX_DEVTOOLS,
  REACT_DEVELOPER_TOOLS,
} from 'electron-devtools-installer';

const { app } = require('electron');

export async function installExtensions() {
  return app.whenReady().then(async () => {
    const forceDownload = !!process.env.UPGRADE_EXTENSIONS;
    const extensions = [REACT_DEVELOPER_TOOLS, REDUX_DEVTOOLS];
    installExtension(extensions, {
      loadExtensionOptions: { allowFileAccess: true },
      forceDownload,
    })
      .then((name) => console.info(`Added Extension:  ${name}`))
      .catch((err) => console.error('An extension error occurred: ', err));
  });
}
```

- Force download extensions into your local machine
```shell
# this is one time only thing to force download extensions into your local machine
UPGRADE_EXTENSIONS=1 yarn dev // or UPGRADE_EXTENSIONS=1 yarn dev or whatever you use
```

- Stop the app

- Start the app normally
```shell
yarn dev // or yarn dev or whatever you use
```

**Comment by automationghost** [comment]
I switched to vite-electron-builder project ... and set it up for react now ...
turns out React Devtools also didnt work there with my component ... the culprit was
that the root id was "app" and not "root ".. in vite electron this is correctly setup ... but since i copied and pasted things over i noticed it first worked .. then didnt ...

<div id="root">

</div>

impossible to find :D .... just discovered by accident

**Comment by automationghost** [comment]
> Redux has always shown up for me, but never React Dev Tools, though they're being installed the same way.
> 
> Running Manjaro Linux and electron 11.4.12 with node 12.18.3 runtime
> 
> Someone let me know if I should make another issue, not going to for now.

I switched to vite-electron-builder project ... and set it up for react now ... since this project is stuck at electron 26 ... 
turns out React Devtools also didnt work there with my component ... the culprit was
that the root id was "app" and not "root" in index.html.. in vite electron this is correctly setup ... but since i copied and pasted things over i noticed it first worked .. then didnt ...

```
<div id="root">

</div>

```
impossible to find :D .... just discovered by accident

**Comment by aluminum1** [comment]
React Dev Tools doesn't work for me. None of the above fixes work. Electron v31.

**Comment by hongyuan1306** [comment]
Me neither with Electron v33. Though  the Redux Dev Tools extension works despite some warnings.

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.

**Comment by pie6k** [comment]
Not sure what's the point of adding 'not planned' on an issue that can be summarized as 'it doesn't work'.

Seems it is not maintained anymore
