### ISSUE TITLE
VueJS devtools don't work after refreshing the window

### ISSUE THREAD

**Issue by rathboma** [MarshallOfSound/electron-devtools-installer#175]
When reloading the window in devmode with webpack I get a 'devtools were disconnected' error, and on a hard-reload the vue devtools freeze:

![image](https://user-images.githubusercontent.com/279769/108580444-14685a00-72f1-11eb-9882-7c2a8579b089.png)

I'm running against Electron 9.4.3.

I appreciate any advice you can offer!

**Comment by IwantLemonTea** [comment]
same problem
I'm running against Electron 21.4.4.

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
