### ISSUE TITLE
Adding support for ELECTRON_MIRROR for offline workflows

### ISSUE THREAD

**Issue by prince-chrismc** [MarshallOfSound/electron-devtools-installer#188]
[@electron/get](https://github.com/electron/get) includes this features which makes many corporate folks happy. Along with [environment veriables](https://github.com/electron/get#using-environment-variables-for-mirror-options) this workflow is a delight since not all machines have access to the internet.

Is this a feature that could be added here? I'd love to open a PR but I just want to make sure it'll be well received first.

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
