### ISSUE TITLE
Update usage in README

### ISSUE THREAD

**Issue by AgainPsychoX** [MarshallOfSound/electron-devtools-installer#198]
Currently usage described in README makes the app fail if building for production (no dev deps). 

![image](https://user-images.githubusercontent.com/23557839/130715213-ecfbc8f2-db04-4676-83ed-3945148a0e86.png)

In my opinion, one of following should be applied:
1. Mention the behaviour for clarity (even while it's close to obvious),
2. Change the installation to install as regular dependency (no `-D`/`--save-dev`)
3. Introduce dynamic loading example, where the extensions are only installed while in development (maybe using `isDev` flag from `electron-is-dev`, or `app.isPackaged`).

-----

For inspiration, in my codebase I use something like:
```ts
app.whenReady().then(async () => {
	if (isDev) {
		const { default: installExtension, REACT_DEVELOPER_TOOLS } = await import('electron-devtools-installer');
		await installExtension(REACT_DEVELOPER_TOOLS);
	}

	createWindow();
	//...
```

**Comment by jrohlandt** [comment]
@AgainPsychoX thanks. I'm using the package based off your example above. 

Just out of curiosity: Why do you recommend in step number two to not install the package as a dev dependency? Shouldn't dynamically loading the package only in dev mode prevent any issues in packaged applications? Or is there something else to take into consideration as well?

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
