### ISSUE TITLE
Uncaught TypeError: Cannot read property 'forEach' of undefined at Object.injectIntoGlobalHook

### ISSUE THREAD

**Issue by Matrixbirds** [MarshallOfSound/electron-devtools-installer#205]
Hi guys, I m using electron-devtools-installer in my electron apps.
### reproduce steps:
1. integration code in electron main code.
```typescript
const installExtension = require("electron-devtools-installer");
// TODO: replace official package version
// when writing this code, electron-devtools-installer has not released the latest version
// Expected version, greater than: v3.1.1
installExtension
    .default([installExtension.REACT_DEVELOPER_TOOLS], {
        loadExtensionOptions: {
            allowFileAccess: true,
        },
    })
    .catch((err: Error) => console.log("added extension failed", err));
```
2. bootstrap main process.

Got Error `Uncaught TypeError: Cannot read property 'forEach' of undefined at Object.injectIntoGlobalHook`.

Found many solutions about this error is indicating when using old verions react devtools, caused the conflict with react [react-refresh/src/ReactFreshRuntime.js](https://github.com/facebook/react/blob/c59c3dfe554dafb64864f3bbcfff6ffe51f32275/packages/react-refresh/src/ReactFreshRuntime.js#L485) 

### Solutions:
We can see the [userData](https://github.com/MarshallOfSound/electron-devtools-installer/blob/19fd4dde8a8e3eb8a50ba4ca242bf3b52e878436/src/utils.ts#L7) is the folder to save the react-devtools in extensions folder. 

1. find the `userData` path.
2. delete extensions folder.
3. re-install react-devtools by `electron-devtools-installer`.

**Comment by Matrixbirds** [comment]
### Suggestion:
1. How to handle notification about old extensions plugin to upgrade the latest version or stable version.

**Comment by julianmesa-gitkraken** [comment]
@Matrixbirds This PR will download the required devtools: https://github.com/MarshallOfSound/electron-devtools-installer/pull/210
At now chrome version passed to the chrome store is 32, so yo get an old devtools

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
