### ISSUE TITLE
Version of Electron: 18.0.2 does not match required range >=1.2.1 for extension ljjemllljcmogpfapbkkighbhhppjdbg

### ISSUE THREAD

**Issue by zelixag** [MarshallOfSound/electron-devtools-installer#221]
Version of Electron: 18.0.2 does not match required range >=1.2.1 for extension ljjemllljcmogpfapbkkighbhhppjdbg

**Comment by Ickerday** [comment]
See https://github.com/MarshallOfSound/electron-devtools-installer/issues/187

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
