### ISSUE TITLE
Naming is not consistent, error prone

### ISSUE THREAD

**Issue by a-x-** [MarshallOfSound/electron-devtools-installer#227]
https://stackoverflow.com/a/73753930/2650114

```
VUEJS_DEVTOOLS
VUEJS3_DEVTOOLS
REDUX_DEVTOOLS
MOBX_DEVTOOLS
```
but:
```
APOLLO_DEVELOPER_TOOLS
REACT_DEVELOPER_TOOLS
```
even more!:
```
CYCLEJS_DEVTOOL
```

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
