### ISSUE TITLE
"Extension server error: Operation failed: Permission denied", source: devtools://devtools/bundled/extensions/extensions.js

### ISSUE THREAD

**Issue by nukeop** [MarshallOfSound/electron-devtools-installer#230]
electron-devtools-installer: 3.2.0
electron: 12

I started getting this error today. Any clue what happened?

**Comment by javierguzman** [comment]
Nobody has a workaround or something?

**Comment by blakewatson** [comment]
Also getting this error.

**Comment by blakewatson** [comment]
I’m still seeing errors but I was eventually able to get Vue devtools to load by serving my `index.html` file on localhost and using `win.loadURL('http://localhost:8080');` rather than `win.loadFile('index.html');`.

I’m only loading it that way in development, of course.

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
