### ISSUE TITLE
Invalid header: Does not start with Cr24

### ISSUE THREAD

**Issue by trek-eric** [MarshallOfSound/electron-devtools-installer#240]
I am unable to use the devtools. After building my application I receive the following in my CLI:

```
Vue Devtools failed to install: Error: Invalid header: Does not start with Cr24
```

After much research, it appears this error has to do with how the library downloads the extension from google?

 I tried inserting the chrome extension id explicitly like so:

```
await installExtension("nhdogjmejiglipccpnnnanhbledajbpd"); 
```
but I still receive the same error

**Comment by gilmarandrade** [comment]
@trek-eric I'm having the same issue.
But in this discussion [issue 238](https://github.com/MarshallOfSound/electron-devtools-installer/issues/238#issuecomment-1485377549) someone created a copy of this repo and resolved the problem.

I installed the [mentioned repo](https://github.com/xupea/electron-devtools-installer) and it worked just fine with vue 3!

**Comment by vedmant** [comment]
Having the same issue, any way to fix this with current repo?

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.

**Comment by KaKi87** [comment]
This being a breaking change, it should have required a major version number increment.
