### ISSUE TITLE
Uncaught Exception: Error: Cannot find module 'electron-devtools-installer'

### ISSUE THREAD

**Issue by ScubaDrew** [MarshallOfSound/electron-devtools-installer#241]
Following the install directions:

```
npm install electron-devtools-installer --save-dev
```

Works like a charm.

However, when we built our electron app in production mode, then we get the following error when we launched the app:

`A JavaScript error occurred in the main process

```
Uncaught Exception:
Error: Cannot find module 'electron-devtools-installer'
Require stack:
- /Applications/CCC.app/Contents/Resources/app.asar/build/electron/main.js
```

How can we get our app to have `electron-devtools-installer` to work when we are developing locally but not break things when we do production builds?

Thanks!

**Comment by xBiei** [comment]
May I see the code containing the installExtension Function?

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.

**Comment by sgoess** [comment]
I had the same issue today after upgrading to @quasar/app-webpack v4 which now uses ESM.

Here's my workaround (electron-main.js):

Remove the "static" `import` statement and use this dynamic one instead:

```
const { installExtension, VUEJS_DEVTOOLS } = process.env.DEV
  ? await import("electron-devtools-installer")
  : {}; 
```

Then install the extension:

```
app.whenReady().then(async () => {
  if (!process.env.DEV) {
    return;
  }

  await installExtension(VUEJS_DEVTOOLS, {
    loadExtensionOptions: {
      allowFileAccess: true,
    },
  });
});
```
