### ISSUE TITLE
Should be updated to conform to proper ESM package

### ISSUE THREAD

**Issue by bouk** [MarshallOfSound/electron-devtools-installer#245]
Hi there, right now I can't use this package in a pure ESM fashion, you can follow this gist to conform to the proper ESM standards: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#how-can-i-make-my-typescript-project-output-esm

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
