### ISSUE TITLE
The console does not display vue_devtools

### ISSUE THREAD

**Issue by Cantaloupe313** [MarshallOfSound/electron-devtools-installer#246]
The Electron+Vite project launches the development environment and opens the console, but the console does not display vue_devtool

**Comment by badspider7** [comment]
I have the same question.

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
