### ISSUE TITLE
Is there an example Electron app showing electron-devtools-installer integration?

### ISSUE THREAD

**Issue by jameshfisher** [MarshallOfSound/electron-devtools-installer#247]
E.g. an `example/` directory, or an `electron-devtools-installer-example` repo, with a complete package of https://github.com/electron/electron-quick-start with `electron-devtools-installer` installed and integrated, so that `npm run start` shows some example dev tools.

I am trying to get `electron-devtools-installer` working with the Electron hello world example with Electron 33.0.2, with no success.

**Comment by MarshallOfSound** [comment]
Hey folks, appreciate your usage of `electron-devtools-installer`. We're going through a bit of spring cleaning and closing out all the old issues that haven't been looked at.

**This doesn't mean I'm ignoring you, it just means I don't have the time to catch up on 4 years of GitHub issue backlog**

If this issue is still impacting you on the **latest** release of `electron-devtools-installer` and a **supported** release of Electron (see https://releases.electronjs.org) please raise a new issue with a solid repro case and detailed instructions.
